### ISSUE TITLE
Any todo examples 

### ISSUE THREAD

**Issue by gedw99** [tylermmorton/torque#1]
Very cool system @tylermmorton 

i am also into htmx.

any examples so I can see the whole stack ?

**Comment by gedw99** [comment]
https://github.com/tylermmorton/torque/tree/master/.www/docsite Is the dog food example .. nice one

**Comment by tylermmorton** [comment]
Hey @gedw99, thanks for your interest 👍🏻

https://github.com/tylermmorton/torque/blob/master/.www/docsite/routes/docs/docs.go

This is probably the best example of htmx usage with torque. The `VaryRender` function is used to render a full html page vs just a fragment for HTMX requests. 

Let me know if you have any other questions 😁

**Comment by gedw99** [comment]
Cheers :)
