### ISSUE TITLE
Feature: Rate Limiting for Route Modules

### ISSUE THREAD

**Issue by tylermmorton** [tylermmorton/torque#3]
Problem:

I often find myself configuring a rate-limiter guard for every route I register with a `torque` app. I think this is a good use case for the `Guard` API but if users end up registering the same guard on all of their endpoints, perhaps that is a sign that the guard logic should be implemented internally to torque.

```go
torque.WithRouteModule("/login",
	&login.RouteModule{
		AuthService: authService,
	},
	torque.WithGuard(guards.ThrottleGuard(
		throttled.PerHour(25),
	)),
),
```

Rough outline of solution

- [ ] Implement rate limiting with sensible defaults using standard library (https://pkg.go.dev/golang.org/x/time/rate) as a part of the router in [router.go](https://github.com/tylermmorton/torque/blob/master/router.go). 
- [ ] Provide an API to consumers for configuring rate limiting. For a route module this could be an additional interface in [module.go](https://github.com/tylermmorton/torque/blob/master/module.go)?
- [ ] Document the new feature and push it to the [docsite](https://github.com/tylermmorton/torque/tree/master/.www/docsite).

**Comment by shashank73744** [comment]
I want to work on this issue.

**Comment by shashank73744** [comment]
I have one question. Do you want it to be per user or overall.

**Comment by tylermmorton** [comment]
Hi @shashank73744! Thanks for taking this on. That is a great question. Currently torque does not have the concept of a user or session. We'll have to lean on identifiers sent via incoming HTTP requests, such as IP address or user agent string. I think picking one of those two would be a great start. Let me know if you need help or have other questions!
