### ISSUE TITLE
Pocketbase: demo

### ISSUE THREAD

**Issue by gedw99** [tylermmorton/torque#5]
You can use htmx with pocketnbase, but why ?

PB gives you the data layer that is reactive.
PB can code gen typed golang code from the a running PB, so then its easy to then use **torque** on top to build you GUI.
PB uses SSE to emit events to the GUI.

https://pocketbase.io/docs/use-as-framework/

https://pocketbase.io/docs/go-database/ 

---

The Golang code gen off PB aspects are here: 
https://github.com/alexisvisco/pocketpase-gen
and
https://github.com/pocketbase/pocketbase/discussions/2697#discussioncomment-7476407

**Comment by tylermmorton** [comment]
Hey @gedw99, I've never used pocketbase but it seems like a great pairing with torque. I've always built my data layers by hand with mongodb so the codegen aspect of this sounds really great. 

It might take me a while to get ramped up and start thinking about how pocketbase might integrate with torque, though. If you have any experience I'd love to see how you're using both tools together.
